import { UserPersona } from "@/types";

export const PRESET_PERSONAS: UserPersona[] = [
  {
    id: "p-member-ieee",
    name: "Rami Troudi (IEEE Member)",
    email: "rami.ieee@insat.u-carthage.tn",
    role: "MEMBER",
    clearance: "III",
    affiliation: "IEEE",
    isProcessed: true,
    status: "ACTIVE",
    strikesCount: 0,
  },
  {
    id: "p-member-unprocessed",
    name: "New Student (Unprocessed)",
    email: "student@insat.u-carthage.tn",
    role: "MEMBER",
    clearance: "I",
    affiliation: "EXTERNAL",
    isProcessed: false,
    status: "ACTIVE",
    strikesCount: 0,
  },
  {
    id: "p-member-eurobot",
    name: "Eurobot Team Lead",
    email: "eurobot.lead@insat.u-carthage.tn",
    role: "OPERATOR",
    clearance: "V",
    affiliation: "EUROBOT",
    isProcessed: true,
    status: "ACTIVE",
    strikesCount: 0,
  },
  {
    id: "p-member-restricted",
    name: "IEEE Member",
    email: "strike.user@insat.u-carthage.tn",
    role: "MEMBER",
    clearance: "III",
    affiliation: "IEEE",
    isProcessed: true,
    status: "ACTIVE",
    strikesCount: 0,
  },
  {
    id: "p-board-logistics",
    name: "Emna Taghlet (Logistics Board)",
    email: "emna.logistics@insat.u-carthage.tn",
    role: "OPERATOR",
    clearance: "V",
    affiliation: "RAS_BOARD",
    isProcessed: true,
    status: "ACTIVE",
    strikesCount: 0,
  },
  {
    id: "p-superadmin-chair",
    name: "Amine Elkadhi (RAS Chairman)",
    email: "chair.ras@insat.u-carthage.tn",
    role: "SUPERADMIN",
    clearance: "VI",
    affiliation: "RAS_BOARD",
    isProcessed: true,
    status: "ACTIVE",
    strikesCount: 0,
  },
];
